image: webdriverio/selenium-standalone
stages:
  - prepare
  - confidence-check
  - trigger

trigger:
  stage: trigger
  script:
    - "curl -X POST --fail -F token=TOKEN -F ref=REF_NAME https://gitlab.com/api/v4/projects/39683989/trigger/pipeline"

prepare:
  stage: prepare
  dependencies:
    - trigger
  script:
    #- wipCommits=`git log --grep=^WIP`; if [ -n "$wipCommits" ]; then echo "WIP commits detected; aborting."; exit 1; fi
    - npm install
  artifacts:
    expire_in: 1 month
    paths:
    - node_modules/

e2e:chrome:
  stage: confidence-check
  services:
   - selenium/standalone-chrome:3.13
  dependencies:
   - prepare
  script:
    - npm run test:headless --host=selenium__standalone-chrome
